
const Images = {
  eventsWalk: require("./eventsWalk.png"),
  Group41: require("./Group41.png"),
  icon: require("./icon.png"),
  Group39: require("./Group39.png"),
  loginBackground: require("./loginBackground.png"),
  forgetpasswordbackground: require("./forgetpasswordbackground.png"),
  languageScreenBackground: require("./languageScreenBackground.png"),
  americaImage: require("./americaImage.png"),
  isrealFlag: require("./isrealFlag.png"),
  image30: require("./image30.png"),
  image301: require("./image301.png"),
  rectangleBackground: require("./rectangleBackground.png"),
  addPostIcon: require("./addPostIcon.png"),
  tabNavIcon: require("./tabNavIcon.png"),
  chatBackGround:require("./chatBackGround.png"),
  userBack:require("./userBack.png"),
  userBack2:require("./userBack2.png"),
  addphoto:require("./addphoto.png"), 
  backiconProfile:require("./backiconProfile.png"),
  lovationIcon:require("./locationIcon.png"),
  Ellipse:require('./Ellipse.png'),
	eventWalking:require('./eventWalking.png'),
	eventSewing:require('./eventSewing.png'),
	eventSport:require('./eventSport.png'),
	CalenderVector:require('./CalenderVector.png'),
	ClockVector:require('./ClockVector.png'),
	backIcon: require('./backIcon.png'), 
  userInfoBottomBox:require('./userInfoBottomBox.png'),
  messageBack:require('./messageBack.png'),
  backIcon2:require('./backIcon2.png'),
  bell:require("./bell.png"),
  chat:require("./chat.png"),
  close:require("./close.png"),
  home:require("./home.png"),
  photo:require("./photo.jpg"),
  search:require("./search.png"),
  menu:require("./menu.png"),
  settings:require("./settings.png"),

 


};
export default Images;
